### ISSUE TITLE
Luis' Code

### ISSUE THREAD

**Issue by papichulo16** [sethb11/Newrepo#23]
https://drive.google.com/drive/folders/1CnZTRz155gFYzuN9e6o_MfTExbvb8JZo?usp=share_link

**Comment by papichulo16** [comment]
[[PromotingLocalBusiness.zip](https://github.com/sethb11/Newrepo/files/13055203/PromotingLocalBusiness.zip)](url)

10/20/2023

**Comment by sethb11** [comment]
Gave me virus, not nice

**Comment by papichulo16** [comment]
[[includes.zip](https://github.com/sethb11/Newrepo/files/13055248/includes.zip)](url)

**Comment by Bobbaloo28** [comment]
🤑
